/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SowRouteImport } from './routes/sow'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as InquireRouteImport } from './routes/inquire'
import { Route as IndexRouteImport } from './routes/index'

const SowRoute = SowRouteImport.update({
  id: '/sow',
  path: '/sow',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const InquireRoute = InquireRouteImport.update({
  id: '/inquire',
  path: '/inquire',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inquire': typeof InquireRoute
  '/portfolio': typeof PortfolioRoute
  '/process': typeof ProcessRoute
  '/sow': typeof SowRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inquire': typeof InquireRoute
  '/portfolio': typeof PortfolioRoute
  '/process': typeof ProcessRoute
  '/sow': typeof SowRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inquire': typeof InquireRoute
  '/portfolio': typeof PortfolioRoute
  '/process': typeof ProcessRoute
  '/sow': typeof SowRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/inquire' | '/portfolio' | '/process' | '/sow'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/inquire' | '/portfolio' | '/process' | '/sow'
  id: '__root__' | '/' | '/inquire' | '/portfolio' | '/process' | '/sow'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InquireRoute: typeof InquireRoute
  PortfolioRoute: typeof PortfolioRoute
  ProcessRoute: typeof ProcessRoute
  SowRoute: typeof SowRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sow': {
      id: '/sow'
      path: '/sow'
      fullPath: '/sow'
      preLoaderRoute: typeof SowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquire': {
      id: '/inquire'
      path: '/inquire'
      fullPath: '/inquire'
      preLoaderRoute: typeof InquireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InquireRoute: InquireRoute,
  PortfolioRoute: PortfolioRoute,
  ProcessRoute: ProcessRoute,
  SowRoute: SowRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
